Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,10 +18,10 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Build
+      - name: Build Docker Image
         run: docker build -t test-image .
 
-      - name: Run
+      - name: Run Docker Container
         run: docker run --rm -d -p 8000:8000 --name test-container test-image
 
       - name: Install dependencies
@@ -30,20 +30,11 @@ jobs:
           pip3 install -r requirements.txt
           pip3 install pytest
 
-      - name: Tests
+      - name: Run Tests
         run: |
-          RUNNING_STATE=$(docker inspect -f '{{.State.Running}}' test-container)
-          echo "Container state: $RUNNING_STATE"
-          if [ "$RUNNING_STATE" == "true" ]; then
-            echo "Container is running."
-          else
-            echo "Container is not running."
-            exit 1
-          fi
           python3 -m pytest tests.py
-          sudo docker stop test-container
 
-      - name: Bump version
+      - name: Bump Version
         id: bump_version
         run: |
           current_version="${{ env.TAG }}"
@@ -51,32 +42,29 @@ jobs:
           version_parts[2]=$((version_parts[2] + 1))
           new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
           echo "new_version=$new_version" >> $GITHUB_ENV
-          
-      - name: Debug Environment Variables
-        run: env
 
-      - name: Log new_version for debugging
+      - name: Log new_version
         run: echo "New version is: ${{ env.new_version }}"
-      
-      - name: Sanitize new_version
+
+      - name: Validate new_version
         run: |
-          sanitized_version=$(echo "${{ env.new_version }}" | tr -cd '[:alnum:].-_')
-          echo "Sanitized version is: $sanitized_version"
-          echo "SANITIZED_NEW_VERSION=$sanitized_version" >> $GITHUB_ENV
-      
-      - name: Renaming the image with the sanitized version
+          if [ -z "${{ env.new_version }}" ]; then
+            echo "Error: new_version is empty."
+            exit 1
+          fi
+
+      - name: Rename Docker Image
         run: |
-          echo "Renaming image to tamarshnirer/shorten-url:${{ env.SANITIZED_NEW_VERSION }}"
-          docker tag test-image:latest "tamarshnirer/shorten-url:${{ env.SANITIZED_NEW_VERSION }}"
-    
+          docker tag test-image:latest "tamarshnirer/shorten-url:${{ env.new_version }}"
+
       - name: Login to DockerHub
         uses: docker/login-action@v2
         with:
           username: tamarshnirer
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      - name: Push image with new tag
-        run: docker push tamarshnirer/shorten-url:${{ env.SANITIZED_NEW_VERSION }}
+      - name: Push Docker Image
+        run: docker push tamarshnirer/shorten-url:${{ env.new_version }}
 
       - name: Checkout Target Repository
         uses: actions/checkout@v4
@@ -88,9 +76,7 @@ jobs:
       - name: Update Deployment File
         run: |
           cd example-gitops
-          NEW_IMAGE="tamarshnirer/shorten-url:${{ env.SANITIZED_NEW_VERSION }}"
-          sed -i "s|image: .*|image: ${NEW_IMAGE}|" shorten-url-dep.yaml
-          cat shorten-url-dep.yaml
+          sed -i "s|image: .*|image: tamarshnirer/shorten-url:${{ env.new_version }}|" shorten-url-dep.yaml
 
       - name: Commit and Push Changes
         run: |
@@ -98,16 +84,5 @@ jobs:
           git config user.name 'github-actions'
           git config user.email 'actions@github.com'
           git add shorten-url-dep.yaml
-          git status
           git commit -m 'Update deployment image' || echo "No changes to commit"
           git push origin main
-
-      - name: Install GitHub CLI
-        run: sudo apt-get install gh
-
-      - name: Update Github Secret
-        uses: NikhilVashistha/update-github-action-secret@v1.0.3
-        with:
-          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
-          secret_name: 'TAG'
-          secret_value: ${{ env.SANITIZED_NEW_VERSION }}
